@echo off
echo Starting Bike RAG...
echo Opening Browser...
start "" "http://127.0.0.1:8000/static/index.html"
echo Starting Server...
.\venv_clean\Scripts\python -m uvicorn server:app --reload
pause
